name: ${project.name}
version: ${project.version}
author: Haileykins
description: Simple Plugin to Handle and Control Players Personal Data
main: me.haileykins.personalinfo.PersonalInfo

commands:
  personalinfo:
    description: Root Command
    aliases: [pi]